# Python for Data Analysis
    
    AUTHOR: Dr. Wes McKinney 

### Chapter 12: Introduction to Modeling Libraries in Python
### **12.4 Introduction to scikit-learn**

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

In [ ]:
# import os
# DIR = "/content/drive/MyDrive/Colab Notebooks/MNA/TC4029 - Ciencia y analítica de datos/Semana 9/Logistic_Regression"
# os.chdir(DIR)

In [1]:
import pandas as pd
import numpy as np

In [2]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')
train.head(4)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S

In [3]:
train.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [5]:
impute_value = train['Age'].median()
train['Age'] = train['Age'].fillna(impute_value)
test['Age'] = test['Age'].fillna(impute_value)

In [6]:
train['IsFemale'] = (train['Sex'] == 'female').astype(int)
test['IsFemale'] = (test['Sex'] == 'female').astype(int)

In [7]:
predictors = ['Pclass', 'IsFemale', 'Age']

X_train = train[predictors]
X_test = test[predictors]
y_train = train['Survived']
y_test = pd.read_csv('gendermodel.csv')['Survived']

In [8]:
y_train[:5]

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [9]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)
y_predict = model.predict(X_test)
y_predict[:10]

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0], dtype=int64)

In [10]:
from sklearn.metrics import confusion_matrix, precision_score, recall_score

print('Confusion matrix:')
print(confusion_matrix(y_test, y_predict))
print('Precision = TP / (TP + FP) = 144 / (144 + 16) = ', precision_score(y_test, y_predict))
print('Recall = TP / (TP + FN) = 144 / (144 + 8)', recall_score(y_test, y_predict))

Confusion matrix:
[[250  16]
 [  8 144]]
Precision = TP / (TP + FP) = 144 / (144 + 16) =  0.9
Recall = TP / (TP + FN) = 144 / (144 + 8) 0.9473684210526315

## Using pipeline

In [11]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')
train[:5]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [12]:
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import FunctionTransformer

train['IsFemale'] = (train['Sex'] == 'female').astype(int)
test['IsFemale'] = (test['Sex'] == 'female').astype(int)

predictors = ['Pclass', 'IsFemale', 'Age']

X_train = train[predictors]
X_test = test[predictors]
y_train = train['Survived']

model = make_pipeline(SimpleImputer(strategy='median'), LogisticRegression())
model.fit(X_train, y_train)
y_predict = model.predict(X_test)

print('Confusion matrix:')
print(confusion_matrix(y_test, y_predict))
print('Precision = TP / (TP + FP) = 144 / (144 + 16) = ', precision_score(y_test, y_predict))
print('Recall = TP / (TP + FN) = 144 / (144 + 8)', recall_score(y_test, y_predict))

Confusion matrix:
[[250  16]
 [  8 144]]
Precision = TP / (TP + FP) = 144 / (144 + 16) =  0.9
Recall = TP / (TP + FN) = 144 / (144 + 8) 0.9473684210526315